spring:
  application:
    name: exp-mservice-discovery
  profiles:
    active: @activeProfile@
  main:
    banner-mode: "off"
    
server:
  port: 8301

logging:
  level:
    .: INFO
    org.springframework: INFO
    org.hibernate.stat: INFO
    org.hibernate.type: INFO
    org.bzu.exp: DEBUG
  file:
    name: /opt/exp/logs/exp-mservice-discovery.log
    max-history: 20 

eureka:
  instance:
    hostname: exp-mservice-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0   
---

spring:
  profiles: dev

---

spring:
  profiles: prod

