spring:
  profiles:
    active: "dev"
  application:    name: exp-mservice1
  main:
    banner-mode: "off"
  jpa:    hibernate:      ddl-auto: create-drop
    show-sql: true
    properties:      hibernate:
        format_sql: true
  datasource:    initialization-mode: always
  mvc:    async:      request-timeout: -1
  
server:
  port: ${port:8003}  servlet:    encoding:      charset: UTF-8
      enabled: true
      force: true
  tomcat:    uri-encoding: UTF-8
          
logging:
  level:
    .: DEBUG
    org.springframework: DEBUG
    org.hibernate.stat: DEBUG
    org.hibernate.type: INFO
    com.bzu: DEBUG
  file:    name: experiment.log
    path: /opt/exp/logs
    max-history: 20       
---

spring:
  profiles: dev
  
  datasource:    url: jdbc:h2:file:C://users//public//exp3;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
  h2:    console:      enabled: true
      path: /h2-console
      settings:        trace: false
        web-allow-others: false
  
  kafka:    bootstrap-servers: localhost:9092    consumer:      group-id: dpms-group 
---

spring:
  profiles: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/supportdb
    username: dpms
    password: 123
  jpa:
    hibernate:      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    database: postgresql
    
     