spring:
  application:
    name: dpms-gateway-service
  profiles:
    active: @activeProfile@
  main:
    banner-mode: "off"

server:
  port: 80

logging:
  level:
    .: INFO
    org.springframework: INFO
    org.hibernate.stat: INFO
    org.hibernate.type: INFO
    com.cisco: INFO
  file:
    name: /opt/dpms/logs/dpms-api-gateway.log
    max-history: 20 

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000
ribbon:
   ReadTimeout: 180000
   connection-timeout: 180000
    
---

spring:
  profiles: "stage"
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dpms-discovery-service:8301/eureka/
  instance:
    hostname: dpms-api-gateway
zuul:
  host:
    connect-timeout-millis: 180000
    connection-request-timeout-millis: 180000
    socket-timeout-millis: 180000
  routes:
    device-support-service:
      path: /device-support-service/**
    documentation-service:
      path: /documentation-service/** 
    feature-service:
      path: /feature-service/**
    team-service:
      path: /team-service/**
    testing-service:
      path: /testing-service/**
    dpms-ui-service:
      path: /**
      strip-prefix: true
              
---

spring:
  profiles: prod
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dpms-discovery-service:8301/eureka/
  instance:
    hostname: dpms-api-gateway

ribbon:
   ReadTimeout: 180000
   connection-timeout: 180000
   
zuul:
  host:
    connect-timeout-millis: 180000
    connection-request-timeout-millis: 180000
    socket-timeout-millis: 180000
  routes:
    device-support-service:
      path: /device-support-service/**
    documentation-service:
      path: /documentation-service/** 
    feature-service:
      path: /feature-service/**
    team-service:
      path: /team-service/**
    testing-service:
      path: /testing-service/**
    dpms-ui-service:
      path: /**
      strip-prefix: true
 
---

spring:
  profiles: stage
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dpms-discovery-service:8301/eureka/
  instance:
    hostname: dpms-api-gateway

ribbon:
   ReadTimeout: 180000
   connection-timeout: 180000
   
zuul:
  host:
    connect-timeout-millis: 180000
    connection-request-timeout-millis: 180000
    socket-timeout-millis: 180000
  routes:
    device-support-service:
      path: /device-support-service/**
    documentation-service:
      path: /documentation-service/** 
    feature-service:
      path: /feature-service/**
    team-service:
      path: /team-service/**
    testing-service:
      path: /testing-service/**
    dpms-ui-service:
      path: /**
      strip-prefix: true