spring:
  application:
    name: exp-mservice-gateway
  profiles:
    active: @activeProfile@
  main:
    banner-mode: "off"

server:
  port: 80

logging:
  level:
    .: INFO
    org.springframework: INFO
    org.hibernate.stat: INFO
    org.hibernate.type: INFO
    org.bzu.exp: DEBUG
  file:
    name: /opt/exp/logs/exp-mservice-gateway.log
    max-history: 20 

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000
ribbon:
   ReadTimeout: 180000
   connection-timeout: 180000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://@eurekaHost@:8301/eureka/
  instance:
    hostname: exp-mservice-gateway    
---

spring:
  profiles: "dev"

zuul:
  host:
    connect-timeout-millis: 180000
    connection-request-timeout-millis: 180000
    socket-timeout-millis: 180000
  routes:
    exp-mservice1:
      path: /exp-mservice1/**
    exp-mservice2:
      path: /exp-mservice2/** 
    exp-mservice3:
      path: /exp-mservice3/**
    exp-mservice4:
      path: /exp-mservice4/**
    exp-mservice5:
      path: /exp-mservice5/**
    exp-mservice6:
      path: /exp-mservice6/**
    exp-mservice7:
      path: /exp-mservice7/** 
              
---

spring:
  profiles: prod
     
zuul:
  host:
    connect-timeout-millis: 180000
    connection-request-timeout-millis: 180000
    socket-timeout-millis: 180000
  routes:
    exp-mservice1:
      path: /exp-mservice1/**
    exp-mservice2:
      path: /exp-mservice2/** 
    exp-mservice3:
      path: /exp-mservice3/**
    exp-mservice4:
      path: /exp-mservice4/**
    exp-mservice5:
      path: /exp-mservice5/**
    exp-mservice6:
      path: /exp-mservice6/**
    exp-mservice7:
      path: /exp-mservice7/** 
 